Add-Type -AssemblyName System.Drawing
$bmp = New-Object System.Drawing.Bitmap(256, 256)
$g = [System.Drawing.Graphics]::FromImage($bmp)
$g.Clear([System.Drawing.Color]::FromArgb(255, 12, 12, 13))
$font = New-Object System.Drawing.Font("Arial", 120)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::Cyan)
$g.DrawString("D", $font, $brush, [float]60, [float]40)
$iconHandle = $bmp.GetHicon()
$icon = [System.Drawing.Icon]::FromHandle($iconHandle)
$stream = New-Object System.IO.FileStream("d:\Projects\Dev-OS-1\electron\assets\icon.ico", [System.IO.FileMode]::Create)
$icon.Save($stream)
$stream.Close()
$bmp.Dispose()
$g.Dispose()
